### ISSUE TITLE
Team17 Review: Traceability to Requirements

### ISSUE THREAD

**Issue by vickysmt** [purefisher/Smart-Serve#12]
In Section 5.3 Traceability Between Test Cases and Requirements, some of the functional requirements listed in the SRS documents are missing, such as ODR 6-7 & 13-18 and MDR 1 & 11-13. Many of the nonfunctional requirements also seem to be missing from the table. It would be better if the system tests cover all of the requirements.

@samm82

**Comment by snusselder** [comment]
More test cases were added to cover more of the requirements. Any requirements that weren't tested for in the test cases were explained why they weren't tested for.
