### ISSUE TITLE
Team17 Review: How test ST-FR-DMT-01 is performed

### ISSUE THREAD

**Issue by LittleVegeDog** [purefisher/Smart-Serve#13]
In the description about how the test ST-FR-DMT-01 will be performed, the document shows that the test should be done after the completion of the test ST-FR-CPT-01 (testing if "no cup present" notification will be received when there is no cup present for the current order). I think it would make more sense if the test ST-FR-DMT-01 will be performed after both test ST-FR-CPT-01 and test ST-FR-CPT-02 are completed, since it is also important to make sure that the "no cup present" notification is removed after a cup is placed and before the system start dispensing a drink.

@samm82

**Comment by snusselder** [comment]
Test ST-FR-DMT-01 is completed after test ST-FR-CPT-01 and ST-FR-CPT-02.
