### ISSUE TITLE
Team17 Review: Some test methods not specific for Nonfunctional Requirements

### ISSUE THREAD

**Issue by JasperLeungGit** [purefisher/Smart-Serve#14]
For some non-functional tests, the method of testing is that testers will report their opinions after using the product (e.g. ST-NFR-UR-02, ST-NFR-PR-02). It doesn't specify how the questions for these responses are asked (in person, via survey, etc.), and how responses will be recorded. For example, a usability survey is an appropriate testing method that could have been specified, and documented in Section 7.2.

@samm82

**Comment by snusselder** [comment]
The appropriate test cases have been updated to specify that a questionnaire will be used for the users to specify their responses to the questions they are asked during testing.
