### ISSUE TITLE
Team17 Review: More tests for Drink Made Test 

### ISSUE THREAD

**Issue by LittleVegeDog** [purefisher/Smart-Serve#15]
The Drink Made Test has covered scenarios where the cup presents in the pouring area is empty or full. However, I think it would be better if the tests could also cover the scenario where the cup present in the pouring area is partially filled. For example, if the operator put a half-filled cup in the pouring area (whether by accident or on purpose) and the machine is pouring the same volume of liquid into the cup as when an empty cup presents, the liquid will also eventually poured out of the cup after the cup is filled during the process of making the drink.

@samm82

**Comment by snusselder** [comment]
Added a test case that checks for a half full cup. The expected behaviour is that Smart Serve will reject this cup as it is still considered a full cup.
