### ISSUE TITLE
Team17 Review: Test Case Derivation for ST-FR-ICT-01

### ISSUE THREAD

**Issue by vickysmt** [purefisher/Smart-Serve#16]
In the Ingredient Communications Test section, the input for test ST-FR-ICT-01 indicates that ingredient(s) are out of inventory, while the test case derivation says that it is derived from the requirement ODR6 ("User is notified when drink is done"). I was wondering if it should be ODR5 ("User is notified if drink ingredients are out of inventory") in this case.

@samm82

**Comment by RyanW21** [comment]
We have removed ODR6 and updated the VNV plan accordingly
