### ISSUE TITLE
Team17 Review: Nondynamic Testing Used a Necessary

### ISSUE THREAD

**Issue by mikeli0623** [purefisher/Smart-Serve#17]
Would like to see some more non-dynamic testing on top of just dynamic testing, such as static testing, code review, inspections, document review, walkthroughs etc. As per the rubric for the VnV, "detailed and clear plans for evidence beyond dynamic testing are included as appropriate. Nondynamic testing plan is feasible." Right now the testing mostly focuses on dynamic testing and so more nondynamic testing would be good.
@samm82

**Comment by snusselder** [comment]
Non-dynamic testing was added where appropriate.
