### ISSUE TITLE
Team16 Review: System Design - Inconsistencies in 6.4

### ISSUE THREAD

**Issue by jeff-rey-wang** [purefisher/Smart-Serve#42]
Overall, the System Design document looks good! One issue I did notice, however, was that there were some inconsistencies among the requirements listed in 6.4 Connection Between Requirements and Design. In some requirements, the fit criteria were a bit vague; i.e.

**UHR1. Smart Serve must serve the drink at a height that is easy to grab for an average
adult
Design consideration: Smart Serve is designed to be set on a table to ensure it is easy
for the users to grab their drinks.**

What height range does an 'average adult' fall in? I went looking for a fit criteria in your SRS, but couldn't find a condition to definitively check if this requirement is met or not.

Contrastly, 

**PR1. The drink must be ready and served within 45 seconds of when the drink began to
be made
Design consideration: The pumps used in Smart Serve have a flow rate that allow
them to complete a drink in under 45 seconds.**

has a very clear fit criteria, and very clear conditions for meeting the requirement. I would recommend listing a 'fit criteria' under each of these non-functional requirements to clearly communicate how each requirement will be assessed, which may better inform your future design considerations.

**Comment by purefisher** [comment]
done
