### ISSUE TITLE
Team 34 Design Doc Review : System Design Doc Event Handling

### ISSUE THREAD

**Issue by WinnieTrandinh** [purefisher/Smart-Serve#43]
@NickCapstone

Well done with including the undesired event handling within the System Design doc, section 6.2.
However, perhaps more detail could be added on the exact event being caught. 

For example, which events are being caught? How will they be handled? Are they all handled the same way by notifying the operator, or are there some events that the product could handle by itself? And what exactly is the 'safe state' that is mentioned? How does the product behave within this 'safe state'?

**Comment by purefisher** [comment]
fixed
