### ISSUE TITLE
Team 34 Design Doc Review: Detailed Design Doc Uses Subsection

### ISSUE THREAD

**Issue by WinnieTrandinh** [purefisher/Smart-Serve#48]
@NickCapstone

Overall, the MIS was well done with good detail.
However, the 'Uses' subsection on the modules should be on what other modules the module uses, not the purpose of the module.

For example, the Drink Completion Module might have the Python Hardware Module under the 'Uses' section.
The purpose of the module is already described within the system architecture document, so there is minimal benefit in restating its use.

**Comment by PeterMinbashian** [comment]
That's a good point. Thanks!
