### ISSUE TITLE
Team 34 Design Doc Review

### ISSUE THREAD

**Issue by ghost** [purefisher/Smart-Serve#49]
@NickCapstone For your MIS Semantics, I believe there can be more detail on how the modules will work. For example, MIS for Python HW Semantics 8.4.1 State Variables
Drink: Ceasar, Mojito, Margarita, etc... all the cocktails the product can mix
cocktailCreated: cocktailCreated
8.4.2 Environment Variables
All the ingredients can hold but written in variables. 8.4.4 Access Routine Semantics
makeCocktail():-->Ceasar()-->Vodka()-->ClamatoJuice()-->Sauce()-->Ready() output:
If Drink order is sent
and If Cup is at machine
and If Appropriate Ingredients are available
exception: If Ingredients are not available or If Cups not available

Great work. Can't wait for this demo.

**Comment by PeterMinbashian** [comment]
Noted, alterations were made. Thanks for the feedback.
