### ISSUE TITLE
Team 15 Review: Results of NFR system tests

### ISSUE THREAD

**Issue by agentvv** [purefisher/Smart-Serve#65]
At the beginning of the NFR system tests section you mention that "All test results are qualitative and not measured" and so the results are simply pass or fail, but many of the tests do have quantitative values assigned to them. Some of the tests have this quantitative data mentioned in the Actual Outputs section (ST-NFR-PR-01, ST-NFR-PR-02), but many do not. It would be useful to add this data so that readers of your document can get a better sense of the performance of your project.

@samm82

**Comment by snusselder** [comment]
Tests where quantitative data was mentioned as an output was discussed and included in the potential output to not confuse the reader.
