### ISSUE TITLE
Team15 Review: No Design Document VNV

### ISSUE THREAD

**Issue by Adham-Badawy** [purefisher/Smart-Serve#66]
Hey guys, it might be more accurate to categorize this as an issue for the VNV Plan and not the VNV Report, but I figure its close enough that it bears mentioning here. I notice there is no mention of any document reviews in your report, only implementation testing. Assuming you are basing your implementation off of your prior design documents, it might not be a bad idea to perform a quick review of things like your SRS or Hazard Analysis to make sure they still align with what you're doing.  As a bonus it makes it easier to figure out what you need to change for the Rev1 documentation. 
@samm82

**Comment by snusselder** [comment]
The SRS, Hazard Analysis, VnV Plan and VnV Report were updated and ensured that they align completely.
