### ISSUE TITLE
Team 15 Review: Requirement testing

### ISSUE THREAD

**Issue by f1377v** [purefisher/Smart-Serve#67]
In the tables where you reported the system tests I would use "User Action" instead of "input" as that is a more suitable title for what is described in that column. Also, It might make more sense to explain the scoring system inside expected result rather than input. For example, in expected result you'd have "The average score from the testers in the survey is greater than 3 on a scale from 1 to 5: 1-unusable 2-poor 3-satisfactory ...".

@samm82

**Comment by snusselder** [comment]
The column title was left as inputs as it wasn't always the user running the test, sometimes the operator. The scoring system was explained in more detail.
