### ISSUE TITLE
Team 15 Review: Functional and Non-Functional Testing

### ISSUE THREAD

**Issue by yazdinip** [purefisher/Smart-Serve#68]
One of the aspects that are usually tested through unit testing is boundary and unexpected input handling and as there were no unit testing, I wasn't sure if the inputs are submitted in a specific way that would not really allow bad entries. For each of the functional requirements, there are system tests that can be written to verify them. Similarly for the non-functional requirements, quantitative methods should be included such as performance. Small things but hope it helps.  

@samm82

**Comment by snusselder** [comment]
These boundary test cases were incorporated into the revised VnV Report document.
