### ISSUE TITLE
Team 18 HA Review: Contradiction in Container Material

### ISSUE THREAD

**Issue by charlottechengg** [purefisher/Smart-Serve#7]
The critical assumption states that "All drinking containers are made of plastic", however in the FMEA table it is using glass when referring to containers. If the containers are made of glass, then your hazard analysis should probably also include hazards related to the handling of glassware. Injuries to the hand are the most frequent occurrence when handling glassware, ranging from minor cuts to more serious injuries, such as puncture wounds. If the container is made of plastic, disposal of used plastic containers might also need to be considered.

**Comment by charlottechengg** [comment]
@purefisher can you please create a label for our team?

**Comment by snusselder** [comment]
@charlottechengg the label has been created
